### ISSUE TITLE
ImportError: No module named 'fused'

### ISSUE THREAD

**Issue by Zhtuzki** [rosinality/swapping-autoencoder-pytorch#24]
I encountered this problem. Thank you very much for helping me!
Traceback (most recent call last):
  File "C:/Users/zhanggeng/Desktop/swapping-autoencoder-pytorch-master/train.py", line 21, in <module>
    from model import Encoder, Generator, Discriminator, CooccurDiscriminator
  File "C:\Users\zhanggeng\Desktop\swapping-autoencoder-pytorch-master\model.py", line 7, in <module>
    from stylegan2.model import StyledConv, Blur, EqualLinear, EqualConv2d, ScaledLeakyReLU
  File "C:\Users\zhanggeng\Desktop\swapping-autoencoder-pytorch-master\stylegan2\model.py", line 11, in <module>
    from .op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "C:\Users\zhanggeng\Desktop\swapping-autoencoder-pytorch-master\stylegan2\op\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "C:\Users\zhanggeng\Desktop\swapping-autoencoder-pytorch-master\stylegan2\op\fused_act.py", line 15, in <module>
    os.path.join(module_path, "fused_bias_act_kernel.cu"),
  File "E:\Anaconda\ANACONDA\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 680, in load
    is_python_module)
  File "E:\Anaconda\ANACONDA\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 877, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "E:\Anaconda\ANACONDA\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1084, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "E:\Anaconda\ANACONDA\envs\pytorch\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'fused'

**Comment by Zhtuzki** [comment]
I cant find module named 'fused'
