### ISSUE TITLE
Add colab or checkpoints

### ISSUE THREAD

**Issue by AlexRMU** [rosinality/swapping-autoencoder-pytorch#8]
Hello
Add colab or checkpoints, please

**Comment by rosinality** [comment]
You can use this: https://drive.google.com/file/d/1JkQHADB-jydOyWVdlnvkVPSvTAjo9fE_/view?usp=sharing

**Comment by AlexRMU** [comment]
Like this?
`!python generate.py --ckpt /070000.pt /01.png /02.jpg `

It outputs
```
Traceback (most recent call last):
  File "generate.py", line 91, in <module>
    "/root/works/sandbox/swapping-autoencoder/Px437_IBM_VGA_8x16.ttf", 16
  File "/usr/local/lib/python3.6/dist-packages/PIL/ImageFont.py", line 642, in truetype
    return freetype(font)
  File "/usr/local/lib/python3.6/dist-packages/PIL/ImageFont.py", line 639, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python3.6/dist-packages/PIL/ImageFont.py", line 188, in __init__
    font, size, index, encoding, layout_engine=layout_engine
OSError: cannot open resource
```
